partner_contact_tradename: migrate to 15.0
OCA/l10n-ecuador pull request #27
Opened 2022-02-07 03:39 UTC by patovala

- Add partner_contact tradename field
- Add unit tests for field and search method

2022-02-10 22:45 UTC, celm1990 requested changes

2022-02-10 22:45 UTC, celm1990 commented on partner_contact_tradename/models/res_partner.py
> +    )
Deberiamos usar un prefijo` l10n_ec_@nombre_campo` para evitar posibles conflictos en algun otro modulo

2022-02-10 22:45 UTC, celm1990 commented on partner_contact_tradename/views/res_partner.xml
> +    <data>
Etiqueta `data` ya no es necesario

2022-02-10 22:45 UTC, celm1990 commented on partner_contact_tradename/views/res_partner.xml
> +                <data>
Etiqueta `data` ya no es necesario

2022-02-10 22:45 UTC, celm1990 commented on partner_contact_tradename/views/res_partner.xml
> +                <data>
Etiqueta `data` ya no es necesario

2022-02-10 22:45 UTC, celm1990 commented on partner_contact_tradename/views/res_partner.xml
> +            <field name="type">search</field>
Etiqueta `type` ya no es necesario

2022-02-10 22:45 UTC, celm1990 commented on partner_contact_tradename/views/res_partner.xml
> +            <field name="type">tree</field>
Etiqueta `type` ya no es necesario

2022-02-10 22:45 UTC, celm1990 commented on partner_contact_tradename/README.rst
> +`here <https://github.com/OCA/partner-contact/issues/new?body=module:%20partner_contact_tradename%0Aversion:%209.0%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expecte
Porque ca se hace referencia a otro repositorio `partner-contact`???

2022-02-11 20:43 UTC, damendieta commented on partner_contact_tradename/README.rst
> +`here <https://github.com/OCA/partner-contact/issues/new?body=module:%20partner_contact_tradename%0Aversion:%209.0%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expecte
Este módulo debería estar en el repositorio partner-contact puesto que no es algo específico del Ecuador, el nombre comercial es un concepto genérico.

2022-02-11 23:33 UTC, patovala commented on partner_contact_tradename/views/res_partner.xml
> +            <field name="type">search</field>
podrías referenciar la razón? link al deprecado?

2022-02-11 23:35 UTC, patovala commented on partner_contact_tradename/models/res_partner.py
> +    )
? podrías especificar en donde? el tradename parece ser un campo bien genérico, pero tampoco lo podemos prefijar en la forma en que lo propones

2022-02-11 23:36 UTC, patovala commented on partner_contact_tradename/models/res_partner.py
> +    )
@damendieta mas bien no me gusta mucho que quede el nombre del label en español, podría usarse algo con _() para localizarlo? algun link a como lo hacen otros módulos?

2022-02-12 02:42 UTC, damendieta reviewed
@patovala falta agregar tu nombre a los autores y contribuidores.

2022-02-12 02:42 UTC, damendieta commented on partner_contact_tradename/README.rst
> +===================================
El tamaño de los === debe ser igual al del nombre

2022-02-12 02:42 UTC, damendieta commented on partner_contact_tradename/models/res_partner.py
> +        "Nombre comercial",
Si, el nombre debería estar en inglés y debe tener una traducción al español

2022-02-12 02:42 UTC, damendieta commented on partner_contact_tradename/models/res_partner.py
> +    )
> Deberiamos usar un prefijo` l10n_ec_@nombre_campo` para evitar posibles conflictos en algun otro modulo

el campo tradename debe ser genérico pues no es parte de la localización, no es un nombre comercial ecuatoriano. Este módulo debe pasar al repositorio partner-contact.

2022-02-12 16:40 UTC, celm1990 commented on partner_contact_tradename/models/res_partner.py
> +    )
> ? podrías especificar en donde? el tradename parece ser un campo bien genérico, pero tampoco lo podemos prefijar en la forma en que lo propones

Si es generico y se va a mover a otro repositrio omitimos el prefijo l10n_ec, si es algo especifico de ecuador mi sugerencia era usar ese prefijo

2022-02-12 17:05 UTC, celm1990 commented on partner_contact_tradename/views/res_partner.xml
> +            <field name="type">search</field>
Esto viene desde la V8 o algo asi, el `type `de la vista se determina automaticamente desde el tag que tenga el arch. Si revisas las vistas de Odoo ninguna se especfiica un `type`, xq dentro del arch ya defines si es tree,form,search, etc y especificar el type es confuso/redundante.

Primer commit que convirtio el campo en un compute(funcion en la vieja API), https://github.com/odoo/odoo/commit/ebf13837858f3572f0d4959d639a4f47d32935ba
luego paso a ser un campo normal nuevamente pero desconosco el commit especifico 


pero si revisar el codigo, en el `create `se toma el type desde el arch automaticamente https://github.com/odoo/odoo/blob/15.0/odoo/addons/base/models/ir_ui_view.py#L507-L519

Mi comentario va orientado a actualizar el codigo que posiblemente estes tomando de una version antigua de Odoo, pero no es algo que cause problemas.

2022-02-14 20:25 UTC, patovala commented on partner_contact_tradename/models/res_partner.py
> +    )
el prefijo queda sobre entendido desde el momento en que se lo pone en este repo, es mi sugerencia, mas bien estuve revisando otras localizaciones como esta: https://github.com/OCA/l10n-spain/blob/15.0/l10n_es_partner/models/res_partner.py y veo que ya tienen un field comercial que en nuestro caso es tradename @damendieta

2022-02-14 20:50 UTC, patovala commented on partner_contact_tradename/views/res_partner.xml
> +            <field name="type">search</field>
me queda claro @celm1990 me voy a dar una vuelta por el manual de referencia (https://www.odoo.com/documentation/15.0/developer/reference/backend/views.html), si tienen alguna otra referencia donde se hable de este tema por fa compartir, voy a actualizar mi Pull Request

2022-02-18 16:04 UTC, patovala commented on partner_contact_tradename/models/res_partner.py
> +    )
voy a dar por resuelto los tickets y abrir el PR

2022-02-18 19:04 UTC, patovala commented on partner_contact_tradename/README.rst
> +`here <https://github.com/OCA/partner-contact/issues/new?body=module:%20partner_contact_tradename%0Aversion:%209.0%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expecte
el mismo módulo lo tiene l10n-spain, creo que si debe ir aquí... o?

2022-02-19 02:31 UTC, celm1990 approved these changes
LGTM

2022-02-19 02:31 UTC, celm1990 commented on partner_contact_tradename/views/res_partner.xml
> +        <field name="type">tree</field>
`type `no necesario como comente anteriormente

2022-02-21 15:50 UTC, rafaelbn commented
Hello, just curiosity 😄 .  Why don't you put this module in https://github.com/OCA/partner-contact ? It is exclusive of Ecuador?

2022-02-21 16:00 UTC, patovala commented
> Hello, just curiosity 😄 . Why don't you put this module in https://github.com/OCA/partner-contact ? It is exclusive of Ecuador?

Actually there are other localizations doing kind of the same thing (https://github.com/OCA/l10n-spain/blob/15.0/l10n_es_partner/models/res_partner.py#L14) I'm kind of following the conventions.

2022-02-21 16:27 UTC, celm1990 commented
> Hello, just curiosity 😄 . Why don't you put this module in https://github.com/OCA/partner-contact ? It is exclusive of Ecuador?

Hi @rafaelbn on previous comments(https://github.com/OCA/l10n-ecuador/pull/27#discussion_r804991962) was suggested by @damendieta .

So it is possible merge PR  if it is do  in `partner-contact`, what do you think?

2022-02-21 20:08 UTC, rafaelbn commented
You can do it how you need 😄 

If you make it like this PR and as @patovala point here: https://github.com/OCA/l10n-ecuador/pull/27#issuecomment-1047025582  Then rename the module to `l10n_ec_partner_contact_tradename`

If you want to propose it in `partner-contact` then this name is perfect

Welcome and enjoy!

2022-02-22 18:23 UTC, damendieta commented
> You can do it how you need smile
> 
> If you make it like this PR and as @patovala point here: [#27 (comment)](https://github.com/OCA/l10n-ecuador/pull/27#issuecomment-1047025582) Then rename the module to `l10n_ec_partner_contact_tradename`
> 
> If you want to propose it in `partner-contact` then this name is perfect
> 
> Welcome and enjoy!

This PR should be made in partnert-contact, not here. It's correct, spain has something alike in their repo, but it's something that can be used even without a localization, just to add the tradename to the partner form.

It's better to have one common module instead of adding the same on each localization.

2022-03-06 00:36 UTC, patovala commented
changed to partner-contact repo

2022-03-06 00:36 UTC, closed without merging