[17.0][ADD]: l10n_ec_withhold: new module for Ecuadorian Withholding Taxes
OCA/l10n-ecuador pull request #57
Opened 2023-12-18 01:23 UTC by celm1990

- tax support by invoice line or invoice
- activation by Fiscal Position
- support for Sale and purchase Withholding

TODO: add test for purchase withholding

2023-12-26 19:34 UTC, celm1990 commented
@lojanet @jorge-luis-dev @renbenj29974 @yazber @jgonzalesw @cormaza

This PR is ready for reviews, suggestions and comments are welcome

2023-12-26 19:44 UTC, celm1990 commented
/ocabot migration 10n_ec_withhold

2023-12-26 20:18 UTC, cormaza commented
http://oca-l10n-ecuador-17-0-pr57-f788cda4ece7.runboat.odoo-community.org/web?debug=1#id=53&cids=2&menu_id=137&model=account.move&view_type=form

Issue testing

![image](https://github.com/OCA/l10n-ecuador/assets/1674751/f75bea89-d9c8-4858-8e25-259f58852197)

2023-12-26 20:54 UTC, celm1990 commented
@cormaza 
Could you please provide more details about your test? I observed that the invoice has a tax support of 00, whereas the withholding has two tax supports (01 and 02). During the XML creation process, it to iterate from the withholding line to the invoice lines with the same tax support (and this should be equal, but in this case, it is not).

Could you clarify the expected behavior in this case? It's important to highlight that the supplier is foreign, and currently, this specific scenario is not supported.

2023-12-27 11:53 UTC, cormaza commented
> @cormaza Could you please provide more details about your test? I observed that the invoice has a tax support of 00, whereas the withholding has two tax supports (01 and 02). During the XML creation process, it to iterate from the withholding line to the invoice lines with the same tax support (and this should be equal, but in this case, it is not).
> 
> Could you clarify the expected behavior in this case? It's important to highlight that the supplier is foreign, and currently, this specific scenario is not supported.

I have tested without any instruction, maybe is better get some warnings about these situations, because you know as developer you can explain what is the error, but as user I cannot figure out what is happening only when read code, error only or maybe a wiki can explain better what is the workflow

2024-01-20 15:26 UTC, celm1990 commented
> > @cormaza Could you please provide more details about your test? I observed that the invoice has a tax support of 00, whereas the withholding has two tax supports (01 and 02). During the XML creation process, it to iterate from the withholding line to the invoice lines with the same tax support (and this should be equal, but in this case, it is not).
> > Could you clarify the expected behavior in this case? It's important to highlight that the supplier is foreign, and currently, this specific scenario is not supported.
> 
> I have tested without any instruction, maybe is better get some warnings about these situations, because you know as developer you can explain what is the error, but as user I cannot figure out what is happening only when read code, error only or maybe a wiki can explain better what is the workflow

@cormaza I updated the code to add some validations, could you test again, please

2024-02-05 19:46 UTC, cormaza requested changes

2024-02-05 19:46 UTC, cormaza commented on l10n_ec_withhold/models/account_move.py
> +                    ("ref", "=", move.ref),
This field is used by some process, and other modules, can be other field instead?

2024-02-05 19:46 UTC, cormaza commented on l10n_ec_withhold/models/account_move.py
> +    def unlink(self):
Should be implemented with new decorator like `@api.ondelete(at_uninstall=False)`

2024-02-05 19:46 UTC, cormaza commented on l10n_ec_withhold/models/account_move.py
> +    def _post(self, soft=True):
I suggest use action_post to avoid mistakes in implementation with call to same function

https://github.com/odoo/odoo/blob/17.0/addons/account/models/account_move.py#L4057

2024-02-05 19:46 UTC, cormaza commented on l10n_ec_withhold/models/account_move.py
> +            and self.is_withhold()
I can see you have different comparison in tax_country_code and this code, but should be the same? can be different? maybe with is_withhold method will be enough

2024-02-10 16:33 UTC, celm1990 commented on l10n_ec_withhold/models/account_move.py
> +                    ("ref", "=", move.ref),
Could you provide an example of why you wouldn't want to use this field? `latam_document_number` has constraints, so this field is better. What field do you suggest?

2024-02-10 16:38 UTC, celm1990 commented on l10n_ec_withhold/models/account_move.py
> +    def _post(self, soft=True):
I don't understand what the problem is. Inside the function, it evaluates if it really is a withholding. Additionally, account_edi does this within the `_post`
https://github.com/odoo/odoo/blob/ec4cf76d04e73bc54adaf30dae38fc6ce95ab565/addons/account_edi/models/account_move.py#L237-L240

2024-02-10 16:45 UTC, celm1990 commented on l10n_ec_withhold/models/account_move.py
> +            and self.is_withhold()
I will try to use a unified field. Thanks for the observation.

2024-02-17 14:38 UTC, celm1990 commented on l10n_ec_withhold/models/account_move.py
> +    def unlink(self):
done

2024-02-17 14:39 UTC, celm1990 commented on l10n_ec_withhold/models/account_move.py
> +            and self.is_withhold()
done, I use field [country_code](https://github.com/odoo/odoo/blob/e7998d51da233809b4c7e32233e39cec1c6529be/addons/account/models/account_move.py#L254)

2024-02-22 00:04 UTC, jorge-luis-dev approved these changes

2024-04-12 04:22 UTC, yazber commented
Procurement

A purchase settlement is carried out.
Then the retention is made.
In figure 1, it is shown that a detail of the withheld is not being displayed.
![retenciones_compra](https://github.com/OCA/l10n-ecuador/assets/3648230/18e50561-5660-4ee0-ae50-712cd55a272b)

In figure 2, the tax receipt is shown, but the taxable base for the retention and the tax are not reflected
![ride_retenciones_compras](https://github.com/OCA/l10n-ecuador/assets/3648230/7445693c-c607-43bb-b9ed-efdcd778ceee)

2024-06-12 03:18 UTC, celm1990 commented
@yazber I made the changes. Please update your code and test again.

2024-07-23 01:24 UTC, jorge-luis-dev approved these changes

2024-07-23 01:37 UTC, celm1990 commented
/ocabot merge nobump

2024-07-24 01:55 UTC, celm1990 commented
/ocabot merge nobump

2024-07-24 02:04 UTC, celm1990 commented
/ocabot merge nobump

2024-07-24 02:13 UTC, merged