17.0 mig l10n ec delivery note
OCA/l10n-ecuador pull request #58
Opened 2023-12-21 00:08 UTC by jorge-luis-dev

Migration of Delivery Note module

2023-12-26 19:42 UTC, celm1990 commented
/ocabot migration l10n_ec_delivery_note

2024-04-13 14:29 UTC, celm1990 commented
@jorge-luis-dev please rebase your branch to fixes issues relates to taxes

2024-04-16 01:22 UTC, celm1990 requested changes

2024-04-16 01:22 UTC, celm1990 commented on l10n_ec_delivery_note/tests/test_l10n_ec_delivery_note_common.py
> +                form.delivery_date = fields.Date.today()
Usar mejor `fields.Date.context_today(self)` para evitar problemas de UTC

2024-04-16 01:22 UTC, celm1990 commented on l10n_ec_delivery_note/tests/test_l10n_ec_sale_order.py
> +        # ).save()
eliminar codigo obsoleto y que no se usara

2024-04-18 00:57 UTC, jorge-luis-dev commented on l10n_ec_delivery_note/tests/test_l10n_ec_delivery_note_common.py
> +                form.delivery_date = fields.Date.today()
Ya está actualizado

2024-04-18 00:57 UTC, jorge-luis-dev commented on l10n_ec_delivery_note/tests/test_l10n_ec_sale_order.py
> +        # ).save()
Ya está actualizado

2024-04-24 19:24 UTC, sabiduriainformatica commented
Dear Jose Luis

In a delivery note made from sales, the invoice field should be set with the invoice number or allow this invoice number to be selected before authorizing said guide in the SRI.

![image](https://github.com/OCA/l10n-ecuador/assets/75393724/02a800bb-13d8-4566-8319-9eda70fb85f4)

2024-04-25 17:17 UTC, franklingerman approved these changes

2024-04-25 17:19 UTC, franklingerman commented
Dear Jose Luis
The field should be set with the invoice number or allow this invoice number to be selected before authorizing said guide in the SRI.

2024-04-25 21:13 UTC, celm1990 commented
@jorge-luis-dev 
Before the migration process, the user could fill the `invoice_id` field into wizard at this line https://github.com/OCA/l10n-ecuador/blob/2cc2a3eb0abf18ca5ce42456f2a8fbfa7164224e/l10n_ec_delivery_note/wizard/wizard_input_document_number.bak.py#L65 
And is used here
https://github.com/OCA/l10n-ecuador/blob/2cc2a3eb0abf18ca5ce42456f2a8fbfa7164224e/l10n_ec_delivery_note/models/stock_picking.py#L149

However, in the migration process, this wizard is no longer used, so the 'invoice_id' field is never filled in the delivery note. Please review this. If the sale order has an invoice, pass this record to the delivery note.

NOTE: @sabiduriainformatica @franklingerman  This depends on the invoice policy from the product's configuration. You can deliver before creating the invoice and create the invoice later, so this scenario is complicated.

NOTE 2: Picking does not have a direct relation with the invoice, so we will only try to obtain the invoice from the sale order. Other alternative is add dependency to this module https://github.com/OCA/stock-logistics-workflow/tree/17.0/stock_picking_invoice_link what do you think?

2024-04-30 14:23 UTC, eduxworks approved these changes
Lo he probado me parece genial tu aporte.

2024-06-03 02:40 UTC, rjab-odoo approved these changes

2024-06-13 04:57 UTC, rjab-odoo approved these changes

2024-06-14 16:56 UTC, rvjaraj approved these changes
Probado y Aprobado 

Como sugerencia agregar el motivo en el modelo stock.picking

2024-06-14 22:17 UTC, rjab-odoo approved these changes

2024-10-17 03:42 UTC, rjab-odoo approved these changes

2025-01-10 17:24 UTC, closed without merging